### ISSUE TITLE
ON-OFF status toggling on 2016+ TV 

### ISSUE THREAD

**Issue by fbalestrini** [roberodin/ha-samsungtv-custom#23]
Your component works very well with my Samsung TV (). Well done!
However, even if my TV is switched off, the status toggles ON-OFF continuously (see picture below). 

![Samsung-TV-on-off](https://user-images.githubusercontent.com/54440701/71180645-e6156780-2272-11ea-8ce6-84757f211290.png)

This is my current component's configuration:
```
media_player:
  - platform: samsungtv_custom
    name: "TV Samsung"
    host: <IP_ADDRESS>
    mac: <MAC_ADDRESS>
    port: 8002
    protocol: ws
```
