### ISSUE TITLE
ON/OFF detection works, does not respond to basic commands

### ISSUE THREAD

**Issue by geekscrapy** [roberodin/ha-samsungtv-custom#71]
I have the following config and using the Hassio VM (no additional things installed apart from a couple of Integrations), using the version of ha-samsungtv-custom which is available at this time.

The TV ON/OFF state is tracked, but the controls don't work. I have the Q80R QLED.

Config:

```
media_player:
  - platform: samsungtv_custom
    host: 192.168.11.11
    mac: aa:aa:aa:aa:aa:aa
    sourcelist: '{"PlayStation": "KEY_HDMI1", "RaspberryPi": "KEY_HDMI2", "Chromecast": "KEY_HDMI3"}'
    #applist: "YouTube, Apple TV, Plex, Prime Video, Spotify"
    port: 8002
    protocol: ctl_qled
```
I tested pretty much all the combinations of protocol and ports (so, ws on both 8001+8002, ctl_beta on 8001+8002 etc..), with and without the port variables. 

If it makes a difference, the TV is on a different VLAN to Hassio, but as far as I'm aware, this should only limit the turn on feature as I guess that uses WoL.

Side note, what format should the MAC address be in? de:ad:be:ef:de:ad or de-ad-be-ef-de-ad or deadbeefdead?
